sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t hsdayfly/docker-react-app -f Dockerfile.dev

script:
    - docker run -e CI=true hsdayfly/docker-react-app npm run test -- --coverage

after_success:
    - echo "Test success"