FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]


# 순서 : build - run 
# docker build -f Dockerfile.dev ./
# docker run hsdayfly/docker-react-app
# docker run -p 3000:3000 hsdayfly/docker-react-app
# docker run -it -p 3000:3000 hsdayfly/docker-react-app
# docker run -it -p 3000:3000 -v /usr/src/app/node_modules -v $(pwd):/usr/src/app hsdayfly/docker-react-app

# Nginx 

